#!/bin/sh

set +e

PATH=/usr/sbin:/usr/bin:/sbin:/bin

take_a_peek() {

	cat /etc/debian_version 2>&1 | sed -e "s,^,Debian version: ,"

	dpkg --print-architecture 2>&1 | sed -e "s,^,Architecture: ,"

	dpkg-query -W -f='${Version}\n' primesense-nite-nonfree 2>&1 | sed -e "s,^,Package version: ,"

	#strings /usr/lib/primesense-nite-nonfree/FOO 2>&1 | grep LNX | sed -e "s,^,Adobe Flash Player version: ,"

	echo "MD5 checksums:"
	md5sum /var/cache/primesense-nite-nonfree/* 2>&1 | sed -e "s,^,\t,"
	md5sum /usr/lib/primesense-nite-nonfree/* 2>&1 | sed -e "s,^,\t,"
}

take_a_peek >&3 2>&1

