#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
	update-primesense-nite2-nonfree --uninstall || true
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


